[package]
name = "ptv_api"
version = "0.1.0"
edition = "2021"

[dependencies]
sha1 = "0.11.0-pre.4"
hmac = "0.13.0-pre.4"
hex = "0.4.3"
reqwest = { version = "0.12.9", features = ["blocking", "json"] }  # Or the latest version
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
